### ISSUE TITLE
Documentation Available Somewhere?

### ISSUE THREAD

**Issue by frohro** [agustinmartino/wsjtx_transceiver_interface#1]
Hi, 
I read of your post on reddit.  https://www.reddit.com/r/amateurradio/comments/l9m25l/homebrew_ft8_transceiver/
I'm wondering about the rest of your project, the Arduino code, and schematics of your transmitter.  Are they available somewhere?
Thanks for sharing!
Rob
KL7NA

**Comment by agustinmartino** [comment]
Hi Rob

The documentation for the transmitter is in the other project.
https://github.com/agustinmartino/wsjt_transceiver

This project is just the interface for WSJTx. It works with the latest version without modifications in WSJTx.

Regards and 73
Agustin - LU2HES

**Comment by frohro** [comment]
Thank you Agustin!

73,

Rob

KL7NA

On 8/16/21 5:42 AM, agustinmartino wrote:
> CAUTION: This email originated from outside the Walla Walla University 
> email system.
>
> Hi Rob
>
> The documentation for the transmitter is in the other project.
> https://github.com/agustinmartino/wsjt_transceiver 
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fagustinmartino%2Fwsjt_transceiver&data=04%7C01%7Crob.frohne%40wallawalla.edu%7C7c5b424c1a1745085d9c08d960b352c9%7Cd958f048e43142779c8debfb75e7aa64%7C0%7C0%7C637647145570481754%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ub4YBofd7ruSno5owc0PggPKN%2BLWUynPKyVuElgnKZM%3D&reserved=0>
>
> This project is just the interface for WSJTx. It works with the latest 
> version without modifications in WSJTx.
>
> Regards and 73
> Agustin - LU2HES
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fagustinmartino%2Fwsjtx_transceiver_interface%2Fissues%2F1%23issuecomment-899478612&data=04%7C01%7Crob.frohne%40wallawalla.edu%7C7c5b424c1a1745085d9c08d960b352c9%7Cd958f048e43142779c8debfb75e7aa64%7C0%7C0%7C637647145570491724%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=D3iVT025hY3AVQTGZlr4gOJLReYXqMsTkr7PlBcqSI4%3D&reserved=0>, 
> or unsubscribe 
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAHS2BLA7FKHXNFILAO7YIDT5EBTTANCNFSM5CGSBMFQ&data=04%7C01%7Crob.frohne%40wallawalla.edu%7C7c5b424c1a1745085d9c08d960b352c9%7Cd958f048e43142779c8debfb75e7aa64%7C0%7C0%7C637647145570491724%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=18km3CdDkh9NkjEvYnMvlsK4mBhyMrZtjrE2HJgQnkY%3D&reserved=0>.
> Triage notifications on the go with GitHub Mobile for iOS 
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Crob.frohne%40wallawalla.edu%7C7c5b424c1a1745085d9c08d960b352c9%7Cd958f048e43142779c8debfb75e7aa64%7C0%7C0%7C637647145570491724%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=M6DOaxSOXu2LYOdEed6eg3xa07YwqvWtEP4LDVjJxTo%3D&reserved=0> 
> or Android 
> <https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Crob.frohne%40wallawalla.edu%7C7c5b424c1a1745085d9c08d960b352c9%7Cd958f048e43142779c8debfb75e7aa64%7C0%7C0%7C637647145570501666%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=m82nBIJFDELG%2FJrYqRNzTgU0OGYr3tp2tK9fEvp43No%3D&reserved=0>.
>
-- 
Rob Frohne, Ph.D. P.E.
E. F. Cross School of Engineering
Walla Walla University
100 SW 4th Street
College Place, WA 99362
(509) 527-2075
